apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: podinfo
  namespace: podinfo
spec:
  minReplicas: 1
  maxReplicas: 8
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: podinfo
spec:
  template:
    spec:
      containers:
        - name: podinfod
          image: ghcr.io/stefanprodan/podinfo:6.1.4
          env:
            - name: PODINFO_UI_COLOR
              value: "#00FF00"
