apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../variants/dev
patches:
  - target:
      kind: Ingress
      name: podinfo-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: podinfodev-51-143-49-95.sslip.io
